wine_pairings = {
    "apple_pie": "Late Harvest Riesling",
    "baby_back_ribs": "Zinfandel",
    "baklava": "Moscato d’Asti",
    "beef_carpaccio": "Nebbiolo",
    "beef_tartare": "Beaujolais",
    "beet_salad": "Pinot Noir",
    "beignets": "Ice Wine",
    "bibimbap": "Grüner Veltliner",
    "bread_pudding": "Tokaji",
    "breakfast_burrito": "Dry Rosé",
    "bruschetta": "Verdicchio",
    "caesar_salad": "Sauvignon Blanc",
    "cannoli": "Vin Santo",
    "caprese_salad": "Chenin Blanc",
    "carrot_cake": "Cream Sherry",
    "ceviche": "Albariño",
    "cheese_plate": "Chardonnay",
    "cheesecake": "Moscato d’Asti",
    "chicken_curry": "Gewürztraminer",
    "chicken_quesadilla": "Zinfandel",
    "chicken_wings": "Syrah",
    "chocolate_cake": "Няма налична препоръка",
    "chocolate_mousse": "Няма налична препоръка",
    "churros": "Няма налична препоръка",
    "clam_chowder": "Няма налична препоръка",
    "club_sandwich": "Pinot Gris",
    "crab_cakes": "Няма налична препоръка",
    "creme_brulee": "Няма налична препоръка",
    "croque_madame": "Няма налична препоръка",
    "cup_cakes": "Няма налична препоръка",
    "deviled_eggs": "Няма налична препоръка",
    "donuts": "Няма налична препоръка",
    "dumplings": "Няма налична препоръка",
    "edamame": "Няма налична препоръка",
    "eggs_benedict": "Няма налична препоръка",
    "escargots": "Няма налична препоръка",
    "falafel": "Няма налична препоръка",
    "filet_mignon": "Cabernet Sauvignon",
    "fish_and_chips": "Chablis",
    "foie_gras": "Sauternes",
    "french_fries": "Няма налична препоръка",
    "french_onion_soup": "Няма налична препоръка",
    "french_toast": "Няма налична препоръка",
    "fried_calamari": "Vermentino",
    "fried_rice": "Няма налична препоръка",
    "frozen_yogurt": "Няма налична препоръка",
    "garlic_bread": "Няма налична препоръка",
    "gnocchi": "Barbera",
    "greek_salad": "Assyrtiko",
    "grilled_cheese_sandwich": "Nero d’Avola",
    "grilled_salmon": "Pinot Noir",
    "guacamole": "Albariño",
    "gyoza": "Няма налична препоръка",
    "hamburger": "Merlot",
    "hot_and_sour_soup": "Няма налична препоръка",
    "hot_dog": "Няма налична препоръка",
    "huevos_rancheros": "Няма налична препоръка",
    "hummus": "Няма налична препоръка",
    "ice_cream": "Няма налична препоръка",
    "lasagna": "Sangiovese",
    "lobster_bisque": "Viognier",
    "lobster_roll_sandwich": "Chardonnay",
    "macaroni_and_cheese": "Chenin Blanc",
    "macarons": "Няма налична препоръка",
    "miso_soup": "Няма налична препоръка",
    "mussels": "Muscat",
    "nachos": "Zinfandel",
    "omelette": "Prosecco",
    "onion_rings": "Няма налична препоръка",
    "oysters": "Champagne",
    "pad_thai": "Riesling",
    "paella": "Tempranillo",
    "pancakes": "Няма налична препоръка",
    "panna_cotta": "Няма налична препоръка",
    "peking_duck": "Pinot Noir",
    "pho": "Pinot Grigio",
    "pizza": "Chianti",
    "pork_chop": "Barbera",
    "poutine": "Няма налична препоръка",
    "prime_rib": "Cabernet Sauvignon",
    "pulled_pork_sandwich": "Shiraz",
    "ramen": "Sake",
    "ravioli": "Lambrusco",
    "red_velvet_cake": "Няма налична препоръка",
    "risotto": "Gavi",
    "samosa": "Няма налична препоръка",
    "sashimi": "Sake",
    "scallops": "Albariño",
    "seaweed_salad": "Няма налична препоръка",
    "shrimp_and_grits": "Viognier",
    "spaghetti_bolognese": "Chianti",
    "spaghetti_carbonara": "Pinot Grigio",
    "spring_rolls": "Gewürztraminer",
    "steak": "Cabernet Sauvignon",
    "strawberry_shortcake": "Brachetto d’Acqui",
    "sushi": "Sake",
    "tacos": "Malbec",
    "takoyaki": "Няма налична препоръка",
    "tiramisu": "Vin Santo",
    "tuna_tartare": "Rosé",
    "waffles": "Няма налична препоръка"
}
